# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disain2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TitileBudilnic(object):
    def setupUi(self, TitileBudilnic):
        TitileBudilnic.setObjectName("TitileBudilnic")
        TitileBudilnic.resize(268, 473)
        TitileBudilnic.setAutoFillBackground(False)
        TitileBudilnic.setStyleSheet("background-color: #56a1cc;")
        TitileBudilnic.setSizeGripEnabled(False)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(TitileBudilnic)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 220, 211, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit.raise_()
        self.lineEdit.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.lineEdit_2.raise_()
        self.lineEdit_2.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.lineEdit_3.raise_()
        self.lineEdit_3.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.lineEdit_4.raise_()
        self.lineEdit_4.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(TitileBudilnic)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 190, 211, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setStyleSheet("font-size: 14px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(TitileBudilnic)
        self.pushButton.setGeometry(QtCore.QRect(130, 270, 111, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #5dabd9;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weidht: bolt;\n"
"    border: none;\n"
"    tex-align: center;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5dd9d9;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #4088db;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(TitileBudilnic)
        self.label_5.setGeometry(QtCore.QRect(40, 330, 201, 71))
        self.label_5.setStyleSheet("font-size: 16px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(TitileBudilnic)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 251, 41))
        self.label_6.setStyleSheet("font-size: 28px;\n"
"font-weight: bolt;\n"
"text-align: left;\n"
"color: white;")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(TitileBudilnic)
        QtCore.QMetaObject.connectSlotsByName(TitileBudilnic)

    def retranslateUi(self, TitileBudilnic):
        _translate = QtCore.QCoreApplication.translate
        TitileBudilnic.setWindowTitle(_translate("TitileBudilnic", "Budilnic v 0.2"))
        self.label.setText(_translate("TitileBudilnic", "Day"))
        self.label_2.setText(_translate("TitileBudilnic", "Month"))
        self.label_3.setText(_translate("TitileBudilnic", "Hour"))
        self.label_4.setText(_translate("TitileBudilnic", "Minutes"))
        self.pushButton.setText(_translate("TitileBudilnic", "OK"))
        self.label_6.setText(_translate("TitileBudilnic", "Set the alarm clock"))

